name: Deploy to AWS S3

on:
  push:
    branches:
      - main
 

env:
  AWS_REGION: ap-south-1  # Change to your preferred AWS region
  S3_BUCKET: webapp-store-github  # Change to your S3 bucket name

jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}  # or use access key ID below
          # Uncomment these if using IAM user credentials instead of OIDC:
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

    
      - name: Deploy to S3
        run: aws s3 sync . s3://${{ env.S3_BUCKET }}/ \
            --exclude ".git*" \
            --exclude "node_modules" \
            --exclude ".github" \
            --exclude "*.md"
          
         
